version: '2'
services:
  # To compile run: docker-compose run --rm arangodb-builder
  arangodb-builder:
    image: arangodb-builder
    build:
      context: ./
      dockerfile: Dockerfile.builder
    volumes:
      - "./:/app"
    #command: bash -c "cd /app/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fPIC && make"

  # To test run: docker-compose run --rm php
  php:
    image: arangodb-php
    depends_on:
      - arangodb-builder
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      arangodb_host: "vst://arangodb:8529"
      arangodb_username: ""
      arangodb_password: ""
      arangodb_dbname: _system
    volumes:
      - "./:/app"
    command: ["vendor/bin/phpunit"]

  arangodb:
    image: arangodb:3.2
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
